### ISSUE TITLE
Crash on Unknown Device Type

### ISSUE THREAD

**Issue by ShamelessWizard** [dkerr64/homebridge-yolink#10]
I found a crash due to unknown device types. 

I have the Siren Alarm, Key Fob and Gate Sensors that were causing a type error to be thrown and eventually homebridge crashes. If I create entries for the unsupported devices and select hide from HomeKit then the errors stop and the server can start. 

I've added some logs, but even with verbose it isn't horribly useful. Additionally, we can probably do some work to get you the data you need to add these devices.

**Comment by ShamelessWizard** [comment]
Here are some logs ...

[8/9/2022, 3:50:57 PM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 2E75) is running on port 51089.
[8/9/2022, 3:50:57 PM] [Sonos] listening on http://0.0.0.0:38171/notify
[8/9/2022, 3:50:57 PM] [Sonos] hardware: x64
[8/9/2022, 3:50:57 PM] [Sonos] os: Fedora Linux 36 (Server Edition)
[8/9/2022, 3:50:57 PM] [Sonos] restored 1 accessories from cache
[8/9/2022, 3:50:58 PM] [Sonos] closed http://0.0.0.0:38171/notify
[8/9/2022, 3:50:58 PM] [Sonos] listening on http://0.0.0.0:38171/notify
[8/9/2022, 3:50:58 PM] [Sonos] found 1 households
[8/9/2022, 3:50:58 PM] [Sonos] Sonos_waguiZ5EVj6BaqwBKYRIyOwwsC: RINCON_7828CAA54E7401400 [192.168.1.123]: associated S2 zoneplayer
[8/9/2022, 3:50:58 PM] [YoLink] Access Token expires in 7200 seconds. We will refresh on requests after 6480 seconds
[8/9/2022, 3:50:58 PM] [YoLink] Starting heartbeat to force access token refresh every 6840 seconds
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getHomeId
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceList
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Dining Room Motion Sensor(d88b4c0200024a1d)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Dining Room Motion Sensor (d88b4c0200024a1d) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Front Door Motion Sensor(d88b4c02000249d2)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Front Door Motion Sensor (d88b4c02000249d2) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Garage Freezer Thermostat(d88b4c020005c67a)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Garage Freezer Thermostat (d88b4c020005c67a) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Garage Motion Sensor(d88b4c020002f248)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Garage Motion Sensor (d88b4c020002f248) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Guest Bath Leak Sensor(d88b4c0200052887)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Guest Bath Leak Sensor (d88b4c0200052887) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Guest Bath Leak Sensor 2(d88b4c02000682c4)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Guest Bath Leak Sensor 2 (d88b4c02000682c4) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Guest Bath Leak Sensor 3(d88b4c0200068297)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Guest Bath Leak Sensor 3 (d88b4c0200068297) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Hot Water Tank Leak Sensor(d88b4c02000682c9)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Hot Water Tank Leak Sensor (d88b4c02000682c9) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Kitchen Freezer Thermostat(d88b4c0200055501)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Kitchen Freezer Thermostat (d88b4c0200055501) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Kitchen Leak Sensor(d88b4c0200053460)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Kitchen Leak Sensor (d88b4c0200053460) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Kitchen Motion Sensor(d88b4c020002f130)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Kitchen Motion Sensor (d88b4c020002f130) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Living Room Motion Sensor(d88b4c02000248bd)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Living Room Motion Sensor (d88b4c02000248bd) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Master Bath Sink(d88b4c0200053451)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Master Bath Sink (d88b4c0200053451) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Master Bath Toilet Leak Sensor(d88b4c020005286d)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Master Bath Toilet Leak Sensor (d88b4c020005286d) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Restroom Leak Sensor(d88b4c0200053c34)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Restroom Leak Sensor (d88b4c0200053c34) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Restroom Sink Leak(d88b4c02000533c1)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Restroom Sink Leak (d88b4c02000533c1) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: Utility Room Motion Sensor(d88b4c020002efe4)
[8/9/2022, 3:50:58 PM] [YoLink] Data refresh timer for Utility Room Motion Sensor (d88b4c020002efe4) fired
[8/9/2022, 3:50:58 PM] [YoLink] Restoring accessory from cache: YoLink Fob(d88b4c0100038868)
[8/9/2022, 3:50:58 PM] TypeError: Cannot read properties of undefined (reading 'warn')
    at new YoLinkPlatformAccessory (/usr/lib/node_modules/homebridge-yolink/src/platformAccessory.ts:58:16)
    at YoLinkHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-yolink/src/platform.ts:175:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Dining Room Motion Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Dining Room Motion Sensor' (d88b4c0200024a1d)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Front Door Motion Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Front Door Motion Sensor' (d88b4c02000249d2)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Garage Freezer Thermostat (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Garage Freezer Thermostat' (d88b4c020005c67a)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Garage Motion Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Garage Motion Sensor' (d88b4c020002f248)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Guest Bath Leak Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Guest Bath Leak Sensor' (d88b4c0200052887)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Guest Bath Leak Sensor 2 (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Guest Bath Leak Sensor 2' (d88b4c02000682c4)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Guest Bath Leak Sensor 3 (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Guest Bath Leak Sensor 3' (d88b4c0200068297)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Hot Water Tank Leak Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Hot Water Tank Leak Sensor' (d88b4c02000682c9)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Kitchen Freezer Thermostat (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Kitchen Freezer Thermostat' (d88b4c0200055501)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Kitchen Leak Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Kitchen Leak Sensor' (d88b4c0200053460)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Kitchen Motion Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Kitchen Motion Sensor' (d88b4c020002f130)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Living Room Motion Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Living Room Motion Sensor' (d88b4c02000248bd)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Master Bath Sink (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Master Bath Sink' (d88b4c0200053451)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Master Bath Toilet Leak Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Master Bath Toilet Leak Sensor' (d88b4c020005286d)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Restroom Leak Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Restroom Leak Sensor' (d88b4c0200053c34)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Restroom Sink Leak (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Restroom Sink Leak' (d88b4c02000533c1)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState for Utility Room Motion Sensor (refresh after 14500 seconds)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getDeviceState for 'Utility Room Motion Sensor' (d88b4c020002efe4)
[8/9/2022, 3:50:58 PM] [YoLink] YoLinkAPI.getAccessToken
[8/9/2022, 3:50:58 PM] Got SIGTERM, shutting down Homebridge...
[8/9/2022, 3:50:58 PM] [Sonos] closed http://0.0.0.0:38171/notify
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState received data for Front Door Motion Sensor (d88b4c02000249d2)
[8/9/2022, 3:50:58 PM] [YoLink] Device state for Front Door Motion Sensor (d88b4c02000249d2) is: normal
[8/9/2022, 3:50:58 PM] [YoLink] Set data refresh timer for Front Door Motion Sensor (d88b4c02000249d2) to run in 14500 seconds
[8/9/2022, 3:50:58 PM] [YoLink] checkDeviceState received data for Garage Motion Sensor (d88b4c020002f248)

**Comment by dkerr64** [comment]
Thanks for reporting the bug.  Crash is bad, I had intended to gracefully report when an unknown device was found, clearly I don't have it right yet.

Can you turn on debug please (in the UI select ... menu at top right, then homebridge settings, and turn on debug mode) then (without hiding any device) capture for me the debug statements for each of the devices that start with "SENDING:" and "RECEIVED:" this will tell me what YoLink is sending back for each device and with that I can start to add support for them.

Thanks
David.

**Comment by ShamelessWizard** [comment]
I know how to handle this in python and raise the error rather then let TypeError bubble up, but I can't offer much 'good' help in js. 

I have scrubbed the log. I'm a little worried about the response back. Worst case, I may need to enable each failing device and get you a new log for each one.

here is a map of the unknown devices to keep things sane.

Name: Front Gate
EUI: d88b4c010003e4d9
Model: YS7707-UC
Type: Door Sensor

Name: Side Gate
EUI: d88b4c0100043de0
Model: YS7707-UC
Type: Door Sensor


Name: YoLink Fob
Type: YoLink Fob
EUI: d88b4c0100038868
Model: YS3604-UC


Name: Siren Alarm
Type: Siren Alarm
EUI: d88b4c010003b80d
Model: YS7103-UC



[homebridge.log](https://github.com/dkerr64/homebridge-yolink/files/9295029/ho`mebridge.log)

**Comment by dkerr64** [comment]
Okay, so I see why it crashed, my fault.  Let me push a fix for that so it doesn't crash.  Then I can work with you on adding support for those new devices.

**Comment by dkerr64** [comment]
I have (hopefully) fixed the crash in version 1.0.7 that I just published.  Please install that.  I have also opened three new issues to track adding support for the door sensor, siren and key fob.  Please add into those issues the details I need to implement support... specifically the logs that give me the SENDING and RECEIVED data, plus any MQTT messages that are received, I need those too (pressing a button on your key fob should generate a MQTT message), triggering a gate open/close should also generate message, etc.

**Comment by ShamelessWizard** [comment]
Will do.. I will even generate a siren alarm as much as it pains me.

**Comment by ShamelessWizard** [comment]
Here is the log after removing devices and restarting.

Somehow, only my last update went through.  I will generate the events in the next log.

Build is working.

[homebridge.log](https://github.com/dkerr64/homebridge-yolink/files/9295525/homebridge.log)

**Comment by dkerr64** [comment]
Thanks for the log.  There is enough here for me to get the skeleton in place to support these devices.  Please wait a few days for that, I'll get back to you when I'm ready for next test.
